#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ ! -f "Brewfile" ] && [ "$(uname -s)" = "Linux" ] && [ -e "/etc/lsb-release" ]; then

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/linuxbrew/go/install)" \
</dev/null

touch Brewfile
echo "brew 'rbenv'" >> Brewfile
echo "brew 'ruby-build'" >> Brewfile
cat Brewfile

fi

if [ ! -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" \
</dev/null

touch Brewfile
echo "brew 'rbenv'" >> Brewfile
echo "brew 'ruby-build'" >> Brewfile
cat Brewfile
fi

if [  -f "Brewfile" ] && [ "$(uname -s)" = "Linux" ] && [ -e "/etc/lsb-release" ]; then

echo "$PATH"
  brew update

  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew update

  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

if [ -f ".ruby-version" ] && [ -z "$(rbenv version-name 2>/dev/null)" ]; then
  echo "==> Installing Ruby…"
  rbenv install --skip-existing
  which bundle >/dev/null 2>&1  || {
    gem install bundler
    rbenv rehash
  }
fi

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies…"
  bundle check --path vendor/gems >/dev/null 2>&1  || {
    bundle install --path vendor/gems --quiet --without production --binstubs
  }
fi

