#!/bin/bash

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

source 'shell/utils.sh'  || exit 1

declare OS
OS="$(get_os)"

if [ ! -f "Brewfile" ]; then
    cat os/"$OS"/brew/Brewfile > Brewfile
fi

if [  -f "Brewfile" ]; then
    os/"$OS"/brew/install.sh
    os/"$OS"/brew/bundle.sh
fi

if [ ! -f ".ruby-version" ] ; then
    cat os/"$OS"/rbenv/.ruby-version > .ruby-version
fi

if [ -f ".ruby-version" ] && [ -z "$(rbenv version-name 2>/dev/null)" ]; then
  echo "==> Installing Ruby…"
  rbenv install --skip-existing
  which bundle >/dev/null 2>&1  || {
    gem install bundler
    rbenv rehash
  }
fi

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies…"
  bundle check --path vendor/gems >/dev/null 2>&1  || {
    bundle install --path vendor/gems --quiet --without production --binstubs
  }
fi

